apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubot-chat-web
spec:
  selector:
    matchLabels:
      app: hubot-chat-web
  replicas: 1
  template:
    metadata:
      labels:
        app: hubot-chat-web
    spec:
      containers:
      - name: hubot-chat-web
        image: local/hubot-chat-web:0.1.1
        imagePullPolicy: IfNotPresent
        env:
        - name: PORT
          value: "8080"
        - name: NODE_ENV
          value: "production"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hubot-chat-web-service
spec:
  selector:
    app: hubot-chat-web
  ports:
    - protocol: TCP
      port: 8080
